# Travis config for @RsrchBoy's p5 packages.
#
# Kinda.
#
# Chris Weyl <cweyl@alumni.drew.edu> 2015

# use the docker/container based infrastructure
sudo: false

language: perl
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"
   - "5.20"
   - "5.21"

matrix:
   allow_failures:
      - perl: "5.8"
      - perl: "5.21"

branches:
   only:
      - master

env:
   global:
      - CPANM_OPTS="-q --notest --no-man-pages"
      - DISTS="Dist::Zilla::PluginBundle::RSRCHBOY Text::Wrap Task::BeLike::RSRCHBOY DBIx::Class::Schema::Loader"
      - PB_LIB="dzil-cache"

before_install:
   # git bits sometimes needed...
   - TARGET_BRANCH="$PERLBREW_PERL@$PB_LIB/$TRAVIS_BRANCH"
   - git config user.name 'Travis-CI'
   - git config user.email 'travis@nowhere.dne'
   - git config --add remote.origin.fetch "refs/heads/$TARGET_BRANCH:refs/remotes/origin/$TARGET_BRANCH"
   - git config url.git@github.com:.pushInsteadOf git://github.com/

   - perlbrew lib create $PB_LIB
   - perlbrew switch $PERLBREW_PERL@$PB_LIB

install: caching/install

script:
   - encrypted_a0b0a2d64b79_key= encrypted_a0b0a2d64b79_iv= cpanm $CPANM_OPTS $DISTS || { cat ~/.cpanm/build.log ; false ; }
   - echo yes | encrypted_a0b0a2d64b79_key= encrypted_a0b0a2d64b79_iv= cpan

# NOTE that we don't actually decrypt our keys until after the builds; also
# that we clear the "encrypted_*" variables before actually invoking external
# code above.

after_success: caching/after_success
