# Travis config for *building* p5/perlbrew cache tarballs.
#
# Chris Weyl <cweyl@alumni.drew.edu> 2015

# use the docker/container based infrastructure
sudo: false
addons:
   apt:
      packages:
         - s3cmd

language: perl
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"
   - "5.20"
   - "5.22"
   - "5.23"

matrix:
   allow_failures:
      - perl: "5.8"
      - perl: "5.23"

branches:
   except:
      - /@dzil-cache/

env:
   global:
      - CPANM_OPTS="-q --notest --no-man-pages"
      - DISTS="Dist::Zilla::PluginBundle::RSRCHBOY Text::Wrap Task::BeLike::RSRCHBOY DBIx::Class::Schema::Loader"
      - PB_LIB="dzil-cache"

before_install:
   - perlbrew lib create $PB_LIB
   - perlbrew switch $PERLBREW_PERL@$PB_LIB

install: caching/install
script:  caching/script

# NOTE that we don't actually decrypt our keys until after the builds; also
# that we clear the "encrypted_*" variables before actually invoking external
# code above.

after_success: caching/after_success

# vim: ts=3 sw=3
