#!/bin/sh

set -ex

# ensure we have that which we need...
cpanm $CPANM_OPTS Devel::Cover Devel::Cover::Report::Coveralls

# if built-dist exists, then we're a dzil dist and were built/tested in there
[ -d built-dist ] && cd built-dist

unset RELEASE_TESTING AUTHOR_TESTING
HARNESS_PERL_SWITCHES="-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine" prove -lsrv t
cover -summary
cover -report coveralls
