#!/bin/sh

set -ex

# set a number of vars to indicate that no one is driving
export AUTOMATED_TESTING=1
export RELEASE_TESTING=1
export AUTHOR_TESTING=1
export NONINTERACTIVE_TESTING=1

# set up our library structure
perlbrew lib create $PB_LIB
perlbrew switch $PB_DZIL_PERL
perlbrew lib create $PB_LIB

# common git bits sometimes needed
git config user.name 'Travis-CI'
git config user.email 'travis@nowhere.dne'

# pull down our cache
perlbrew switch $PERLBREW_PERL@$PB_LIB
wget -O $PB_TARBALL "http://travis-p5.objects.dreamhost.com/master/$PB_TARBALL"
test -f "$PB_TARBALL" && tar -C $PERLBREW_HOME/libs -jvxf $PB_TARBALL | wc -l
rm $PB_TARBALL

# ...and our
perlbrew switch $PB_DZIL_PERL@$PB_LIB
wget -O $PB_DZIL_TARBALL "http://travis-p5.objects.dreamhost.com/master/$PB_DZIL_TARBALL"
test -f "$PB_DZIL_TARBALL" && tar -C $PERLBREW_HOME/libs -jvxf $PB_DZIL_TARBALL | wc -l
rm $PB_DZIL_TARBALL

perlbrew switch $PERLBREW_PERL@$PB_LIB

# setup cpan
echo yes | cpan > /dev/null

# for DZP LinkCheck
cpanp x
