#!/bin/sh
#
# an install stanza to install dependencies of a dzil-based distribution.

set -ex

# sanity...
perlbrew list

# change to a newer Perl, just for dzil
perlbrew switch $PB_DZIL_PERL@$PB_LIB
. $HOME/perl5/perlbrew/etc/bashrc

if [ "$INSTALL_DEPS_VIA_DZIL" = "" ] ; then
    # not so much install our package as all its prereqs
    cpanm --with-develop --skip-satisfied $CPANM_OPTS --installdeps . 2>&1 | grep -v 'Ignoring unknown extended header keyword'
    grep '^\[' dist.ini | sed -e 's/^\[@/Bundle::/; s/^\[/::/; s/ .*$//; s/\]//; s/^/Dist::Zilla::Plugin/' | sort | uniq | xargs -t cpanm $CPANM_OPTS
else
    dzil authordeps --missing        | xargs -t cpanm $CPANM_OPTS --skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    dzil listdeps --author --missing | xargs -t cpanm $CPANM_OPTS --skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
fi

[ -e dist.ini ] && dzil build --in built-dist

perlbrew switch $TRAVIS_PERL_VERSION@$PB_LIB
. $HOME/perl5/perlbrew/etc/bashrc
