#!/bin/sh

set -ex

openssl aes-256-cbc -K $encrypted_a0b0a2d64b79_key -iv $encrypted_a0b0a2d64b79_iv -in keys/github_id.enc -out keys/github_id -d
chmod 0600 keys/github_id
eval `ssh-agent`
ssh-add ./keys/github_id
git checkout $TRAVIS_BRANCH
git fetch --unshallow ||:
git fetch
git checkout $TARGET_BRANCH || ( git checkout --orphan $TARGET_BRANCH; git reset; rm -rf * )
PB_LIB_DIR=$PERLBREW_HOME/libs/$PERLBREW_PERL@$PB_LIB
PB_TARBALL=$PERLBREW_PERL@$PB_LIB.tar.bz2
rm -rf $PB_LIB_DIR/man
tar -C $PERLBREW_HOME/libs/ -jcf $PB_TARBALL $PERLBREW_PERL@$PB_LIB
ls -lah $PB_TARBALL
git add $PB_TARBALL && git commit -m "add $PB_TARBALL"
git push -u origin $TARGET_BRANCH:$TARGET_BRANCH
