#!/bin/sh

set -ex

# drop our encryption keys and vars and validate
unset `set | grep ^encrypted | awk -F= '{ print $1 }'`
cpanm -v --no-man-pages Test::NoTravisEncVars

# gotta love failing pod tests blowing everything up...
cpanm $CPANM_OPTS TAP::Harness::Restricted || { cat ~/.cpanm/build.log ; false ; }
export HARNESS_SUBCLASS=TAP::Harness::Restricted

# for DZP LinkCheck
cpanm $CPANM_OPTS CPANPLUS || { cat ~/.cpanm/build.log ; false ; }
