#!/bin/sh

set -ex

# make sure we're wiping the vars effectively...
encrypted_a0b0a2d64b79_key= encrypted_a0b0a2d64b79_iv= cpanm $CPANM_OPTS Test::NoTravisEncVars

# gotta love failing pod tests blowing everything up...
encrypted_a0b0a2d64b79_key= encrypted_a0b0a2d64b79_iv= cpanm $CPANM_OPTS TAP::Harness::Restricted || { cat ~/.cpanm/build.log ; false ; }
export HARNESS_SUBCLASS=TAP::Harness::Restricted

# Moose installs in parallel quite nicely.
HARNESS_OPTIONS=j8:c encrypted_a0b0a2d64b79_key= encrypted_a0b0a2d64b79_iv= cpanm $CPANM_OPTS Moose       || { cat ~/.cpanm/build.log ; false ; }
HARNESS_OPTIONS=j8:c encrypted_a0b0a2d64b79_key= encrypted_a0b0a2d64b79_iv= cpanm $CPANM_OPTS Dist::Zilla || { cat ~/.cpanm/build.log ; false ; }

# for DZP LinkCheck
encrypted_a0b0a2d64b79_key= encrypted_a0b0a2d64b79_iv= cpanm $CPANM_OPTS CPANPLUS || { cat ~/.cpanm/build.log ; false ; }
