#!/bin/sh

set -ex
source caching/common

# gotta love failing pod tests blowing everything up...
cpanm $CPANM_OPTS TAP::Harness::Restricted || { cat ~/.cpanm/build.log ; false ; }
export HARNESS_SUBCLASS=TAP::Harness::Restricted

# for DZP LinkCheck
cpanm $CPANM_OPTS CPANPLUS || { cat ~/.cpanm/build.log ; false ; }
